### PR TITLE
rftr(mouse-gesture): use $1 Unistroke Recognizer

### LINKED ISSUE #1842: [Bug]: Mouse gesture does NOT work correctly
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I customized several mouse gestures on the latest Floorp, but found some of them doesn't work correctly, also its gesture trail isn't smooth.

### Reproduction Steps

1. create several new mouse gesture
2. use these created gestures

Image

### Expected Behavior

the gestures works well

### Actual Behavior

5 of these gestures don't work correctly. 
The gesture trail go on growing after I release the right mouse button when mouse gesture complete, press the right mouse button can interrupt its growing(left button can't interrupt).

another issue: its trail isn't smooth.

Image

### Screenshots

https://github.com/user-attachments/assets/bba68d6f-941a-49e1-956f-29db93346d31

### Browser Version

12.0.15

### Operating System

win 11 pro, 24H2, Operating system version 26100.3775, Experience Windows Function Experience Package 1000.26100.66.0

### Additional Context

_No response_

### LINKED ISSUE #2207: [Bug]: Mouse gestures with multiple directions are broken after update
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the browser updated to 12.9.1@146.0.1, mouse gestures that utilize multiple directions got broken: the Changing the newly added sensitivity settings doesn't seem to help either.

### Reproduction Steps

1. Set a gesture to use multiple directions (→↓ for example )
2. Try to use that gesture

### Expected Behavior

The assigned gesture gets triggered

### Actual Behavior

Singular direction gestures get triggered instead

### Screenshots

https://github.com/user-attachments/assets/e1a3de33-1f8c-4f1e-a168-debd882146d3

### Browser Version

12.9.1@146.0.1

### Operating System

Fedora Linux

### Additional Context

Having both directions for the combo free still doesn't trigger the expected gesture (having → and ↓ unassigned and a →↓ combo)

### PR DESCRIPTION
**Pull request by nyanrus**
Use $1 Unistroke Recognizer for better gesture.
Update dependencies as latest.
fix #1842
fix #2207

### CODE REVIEW

**Comment by nyanrus** [comment]
#1842 is not fixed, so WIP

**Comment by nyanrus** [comment]
Tested about `Open Home Page`, `Close Window`, `Stop`(https://developer.mozilla.org/en-US/docs/Web/API/Window/stop), `Bookmark This Page`, `Reopen Closed Tab` so #1842 is fixed.

File: browser-features/chrome/common/mouse-gesture/utils/actions.ts [hunk 1]
```diff
@@ -37,29 +38,6 @@ export const actions: GestureActionRegistration[] = [
     name: "gecko-reload-all-tabs",
     fn: () => window.gBrowser.reloadAllTabs(),
   },
-  {
```
Comment (Ryosuke-Asano) [inline browser-features/chrome/common/mouse-gesture/utils/actions.ts:40]: これは残そ他方がいいでしょう、

Comment (Ryosuke-Asano) [reply browser-features/chrome/common/mouse-gesture/utils/actions.ts:40]: @copilot Can you revert this deletion?

**Comment by Ryosuke-Asano** [comment]
TY
